# Generated by Django 5.0.6 on 2024-06-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotogrfia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotogrfia',
            new_name='data_fotografia',
        ),
    ]
